import json
import os
import re

# Chemin du fichier source JavaScript
profondeurDtMille = [
  {
    "profondeurDtMill": 55.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 55.045,
    "15m": "",
    "12m": 6,
    "9m": 18,
    "6m": 33,
    "3m": 64,
    "GPS": "-",
  },
  {
    "profondeurDtMill": 55.04,
    "15m": "",
    "12m": 4,
    "9m": 14,
    "6m": 30,
    "3m": 59,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 55.035,
    "15m": "",
    "12m": 2,
    "9m": 10,
    "6m": 26,
    "3m": 51,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 55.03,
    "15m": "",
    "12m": "",
    "9m": 7,
    "6m": 21,
    "3m": 47,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 55.025,
    "15m": "",
    "12m": "",
    "9m": 4,
    "6m": 14,
    "3m": 40,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 55.02,
    "15m": "",
    "12m": "",
    "9m": 2,
    "6m": 8,
    "3m": 32,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 55.015,
    "15m": "",
    "12m": "",
    "9m": 1,
    "6m": 4,
    "3m": 20,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 55.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 2,
    "3m": 8,
    "GPS": "H",
  },
  {
    "profondeurDtMill": 55.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 3,
    "GPS": "E",
  },
  {
    "profondeurDtMill": 52.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 52.045,
    "15m": "",
    "12m": 3,
    "9m": 16,
    "6m": 31,
    "3m": 61,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 52.04,
    "15m": "",
    "12m": 1,
    "9m": 12,
    "6m": 28,
    "3m": 55,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 52.035,
    "15m": "",
    "12m": "",
    "9m": 9,
    "6m": 23,
    "3m": 49,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 52.03,
    "15m": "",
    "12m": "",
    "9m": 5,
    "6m": 18,
    "3m": 44,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 52.025,
    "15m": "",
    "12m": "",
    "9m": 2,
    "6m": 12,
    "3m": 38,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 52.02,
    "15m": "",
    "12m": "",
    "9m": 1,
    "6m": 7,
    "3m": 28,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 52.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 4,
    "3m": 16,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 52.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 2,
    "3m": 6,
    "GPS": "G",
  },
  {
    "profondeurDtMill": 52.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 3,
    "GPS": "E",
  },
  {
    "profondeurDtMill": 50.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 50.045,
    "15m": "",
    "12m": 2,
    "9m": 14,
    "6m": 30,
    "3m": 58,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 50.04,
    "15m": "",
    "12m": "",
    "9m": 11,
    "6m": 26,
    "3m": 52,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 50.035,
    "15m": "",
    "12m": "",
    "9m": 6,
    "6m": 22,
    "3m": 48,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 50.03,
    "15m": "",
    "12m": "",
    "9m": 3,
    "6m": 17,
    "3m": 42,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 50.025,
    "15m": "",
    "12m": "",
    "9m": 2,
    "6m": 10,
    "3m": 36,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 50.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 5,
    "3m": 26,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 50.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 3,
    "3m": 14,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 50.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 1,
    "3m": 6,
    "GPS": "G",
  },
  {
    "profondeurDtMill": 50.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "E",
  },
  {
    "profondeurDtMill": 48.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 48.045,
    "15m": "",
    "12m": "",
    "9m": 12,
    "6m": 29,
    "3m": 55,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 48.04,
    "15m": "",
    "12m": "",
    "9m": 8,
    "6m": 24,
    "3m": 50,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 48.035,
    "15m": "",
    "12m": "",
    "9m": 5,
    "6m": 20,
    "3m": 46,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 48.03,
    "15m": "",
    "12m": "",
    "9m": 2,
    "6m": 14,
    "3m": 40,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 48.025,
    "15m": "",
    "12m": "",
    "9m": 1,
    "6m": 8,
    "3m": 34,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 48.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 5,
    "3m": 24,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 48.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 3,
    "3m": 11,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 48.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 1,
    "3m": 5,
    "GPS": "G",
  },
  {
    "profondeurDtMill": 48.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "D",
  },
  {
    "profondeurDtMill": 45.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 45.045,
    "15m": "",
    "12m": "",
    "9m": 8,
    "6m": 25,
    "3m": 52,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 45.04,
    "15m": "",
    "12m": "",
    "9m": 4,
    "6m": 22,
    "3m": 48,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 45.035,
    "15m": "",
    "12m": "",
    "9m": 2,
    "6m": 17,
    "3m": 43,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 45.03,
    "15m": "",
    "12m": "",
    "9m": 1,
    "6m": 11,
    "3m": 37,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 45.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 7,
    "3m": 29,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 45.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 3,
    "3m": 20,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 45.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 2,
    "3m": 9,
    "GPS": "H",
  },
  {
    "profondeurDtMill": 45.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 5,
    "GPS": "F",
  },
  {
    "profondeurDtMill": 45.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 1,
    "GPS": "D",
  },
  {
    "profondeurDtMill": 42.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 42.045,
    "15m": "",
    "12m": "",
    "9m": 4,
    "6m": 22,
    "3m": 49,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 42.04,
    "15m": "",
    "12m": "",
    "9m": 2,
    "6m": 18,
    "3m": 45,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 42.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 13,
    "3m": 40,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 42.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 8,
    "3m": 34,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 42.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 4,
    "3m": 25,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 42.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 2,
    "3m": 16,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 42.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 1,
    "3m": 7,
    "GPS": "H",
  },
  {
    "profondeurDtMill": 42.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 3,
    "GPS": "F",
  },
  {
    "profondeurDtMill": 42.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 1,
    "GPS": "D",
  },
  {
    "profondeurDtMill": 40.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 40.065,
    "15m": "",
    "12m": "",
    "9m": 13,
    "6m": 31,
    "3m": 62,
    "GPS": "-",
  },
  {
    "profondeurDtMill": 40.06,
    "15m": "",
    "12m": "",
    "9m": 9,
    "6m": 30,
    "3m": 58,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 40.055,
    "15m": "",
    "12m": "",
    "9m": 6,
    "6m": 27,
    "3m": 53,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 40.05,
    "15m": "",
    "12m": "",
    "9m": 3,
    "6m": 23,
    "3m": 50,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 40.045,
    "15m": "",
    "12m": "",
    "9m": 1,
    "6m": 20,
    "3m": 46,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 40.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 15,
    "3m": 41,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 40.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 9,
    "3m": 37,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 40.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 5,
    "3m": 30,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 40.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 3,
    "3m": 21,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 40.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 1,
    "3m": 11,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 40.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 5,
    "GPS": "G",
  },
  {
    "profondeurDtMill": 40.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "E",
  },
  {
    "profondeurDtMill": 40.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 38.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 38.065,
    "15m": "",
    "12m": "",
    "9m": 9,
    "6m": 29,
    "3m": 60,
    "GPS": "C",
  },
  {
    "profondeurDtMill": 38.06,
    "15m": "",
    "12m": "",
    "9m": 5,
    "6m": 28,
    "3m": 55,
    "GPS": "E",
  },
  {
    "profondeurDtMill": 38.055,
    "15m": "",
    "12m": "",
    "9m": 3,
    "6m": 24,
    "3m": 50,
    "GPS": "G",
  },
  {
    "profondeurDtMill": 38.05,
    "15m": "",
    "12m": "",
    "9m": 1,
    "6m": 21,
    "3m": 47,
    "GPS": "H",
  },
  {
    "profondeurDtMill": 38.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 17,
    "3m": 43,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 38.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 11,
    "3m": 39,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 38.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 6,
    "3m": 34,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 38.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 3,
    "3m": 26,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 38.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 2,
    "3m": 18,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 38.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 1,
    "3m": 8,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 38.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 4,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 38.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 38.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "P",
  },
  {
    "profondeurDtMill": 35.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 35.065,
    "15m": "",
    "12m": "",
    "9m": 2,
    "6m": 27,
    "3m": 54,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 35.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 24,
    "3m": 50,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 35.055,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 19,
    "3m": 48,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 35.05,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 15,
    "3m": 44,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 35.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 10,
    "3m": 40,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 35.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 6,
    "3m": 35,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 35.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 3,
    "3m": 29,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 35.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 1,
    "3m": 22,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 35.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 13,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 35.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 6,
    "GPS": "H",
  },
  {
    "profondeurDtMill": 35.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 3,
    "GPS": "F",
  },
  {
    "profondeurDtMill": 35.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 1,
    "GPS": "E",
  },
  {
    "profondeurDtMill": 35.009,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 35.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 32.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 32.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 28,
    "3m": 55,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 32.07,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 24,
    "3m": 52,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 32.065,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 20,
    "3m": 49,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 32.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 16,
    "3m": 47,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 32.055,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 12,
    "3m": 44,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 32.05,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 8,
    "3m": 40,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 32.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 4,
    "3m": 36,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 32.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 2,
    "3m": 30,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 32.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 24,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 32.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 16,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 32.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 8,
    "GPS": "H",
  },
  {
    "profondeurDtMill": 32.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 4,
    "GPS": "G",
  },
  {
    "profondeurDtMill": 32.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "F",
  },
  {
    "profondeurDtMill": 32.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 32.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 30.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 30.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 20,
    "3m": 50,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 30.07,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 17,
    "3m": 48,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 30.065,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 14,
    "3m": 46,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 30.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 10,
    "3m": 43,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 30.055,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 6,
    "3m": 39,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 30.05,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 3,
    "3m": 36,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 30.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 1,
    "3m": 31,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 30.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 24,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 30.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 17,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 30.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 9,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 30.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 4,
    "GPS": "H",
  },
  {
    "profondeurDtMill": 30.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "F",
  },
  {
    "profondeurDtMill": 30.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 1,
    "GPS": "E",
  },
  {
    "profondeurDtMill": 30.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 30.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 28.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 28.095,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 26,
    "3m": 58,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 28.09,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 23,
    "3m": 56,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 28.085,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 20,
    "3m": 53,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 28.08,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 17,
    "3m": 50,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 28.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 14,
    "3m": 48,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 28.07,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 11,
    "3m": 46,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 28.065,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 8,
    "3m": 43,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 28.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 4,
    "3m": 40,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 28.055,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 2,
    "3m": 36,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 28.05,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 32,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 28.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 25,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 28.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 19,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 28.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 12,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 28.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 6,
    "GPS": "H",
  },
  {
    "profondeurDtMill": 28.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "G",
  },
  {
    "profondeurDtMill": 28.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 1,
    "GPS": "F",
  },
  {
    "profondeurDtMill": 28.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "E",
  },
  {
    "profondeurDtMill": 28.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 28.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 25.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 25.095,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 14,
    "3m": 51,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 25.09,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 11,
    "3m": 50,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 25.085,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 9,
    "3m": 48,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 25.08,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 7,
    "3m": 45,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 25.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 4,
    "3m": 43,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 25.07,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 1,
    "3m": 41,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 25.065,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 37,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 25.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 32,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 25.055,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 27,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 25.05,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 21,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 25.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 16,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 25.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 10,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 25.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 5,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 25.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "H",
  },
  {
    "profondeurDtMill": 25.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 1,
    "GPS": "F",
  },
  {
    "profondeurDtMill": 25.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "E",
  },
  {
    "profondeurDtMill": 25.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 25.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 25.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 22.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 22.095,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": 2,
    "3m": 46,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 22.09,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 44,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 22.085,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 41,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 22.08,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 37,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 22.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 33,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 22.07,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 29,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 22.065,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 25,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 22.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 20,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 22.055,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 16,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 22.05,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 12,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 22.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 7,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 22.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 22.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "H",
  },
  {
    "profondeurDtMill": 22.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "G",
  },
  {
    "profondeurDtMill": 22.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "F",
  },
  {
    "profondeurDtMill": 22.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "E",
  },
  {
    "profondeurDtMill": 22.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 22.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 22.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 20.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 20.095,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 37,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 20.09,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 34,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 20.085,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 30,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 20.08,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 27,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 20.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 24,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 20.07,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 20,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 20.065,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 16,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 20.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 13,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 20.055,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 9,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 20.05,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 4,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 20.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 1,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 20.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "H",
  },
  {
    "profondeurDtMill": 20.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "G",
  },
  {
    "profondeurDtMill": 20.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "F",
  },
  {
    "profondeurDtMill": 20.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "E",
  },
  {
    "profondeurDtMill": 20.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 20.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 20.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 20.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 18.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 18.13,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 42,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 18.12,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 38,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 18.115,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 36,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 18.11,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 34,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 18.105,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 31,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 18.1,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 28,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 18.095,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 26,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 18.09,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 23,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 18.085,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 21,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 18.08,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 17,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 18.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 14,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 18.07,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 11,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 18.065,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 8,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 18.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 5,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 18.055,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 1,
    "GPS": "I",
  },
  {
    "profondeurDtMill": 18.05,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "H",
  },
  {
    "profondeurDtMill": 18.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "H",
  },
  {
    "profondeurDtMill": 18.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "G",
  },
  {
    "profondeurDtMill": 18.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "F",
  },
  {
    "profondeurDtMill": 18.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "F",
  },
  {
    "profondeurDtMill": 18.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "E",
  },
  {
    "profondeurDtMill": 18.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 18.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 18.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 18.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 15.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 15.13,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 22,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 15.12,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 18,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 15.115,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 17,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 15.11,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 15,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 15.105,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 13,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 15.1,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 11,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 15.095,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 8,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 15.09,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 6,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 15.085,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 4,
    "GPS": "K",
  },
  {
    "profondeurDtMill": 15.08,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "J",
  },
  {
    "profondeurDtMill": 15.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "J",
  },
  {
    "profondeurDtMill": 15.07,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "I",
  },
  {
    "profondeurDtMill": 15.065,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "I",
  },
  {
    "profondeurDtMill": 15.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "H",
  },
  {
    "profondeurDtMill": 15.055,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "H",
  },
  {
    "profondeurDtMill": 15.05,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "G",
  },
  {
    "profondeurDtMill": 15.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "G",
  },
  {
    "profondeurDtMill": 15.04,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "F",
  },
  {
    "profondeurDtMill": 15.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "E",
  },
  {
    "profondeurDtMill": 15.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "E",
  },
  {
    "profondeurDtMill": 15.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 15.02,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 15.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 15.01,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 15.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "A",
  },
  {
    "profondeurDtMill": 12.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 12.315,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 27,
    "GPS": "-",
  },
  {
    "profondeurDtMill": 12.3,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 26,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 12.285,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 24,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 12.27,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 22,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 12.255,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 19,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 12.25,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 18,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 12.24,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 17,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 12.23,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 16,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 12.22,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 15,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 12.21,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 14,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 12.2,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 13,
    "GPS": "O",
  },
  {
    "profondeurDtMill": 12.19,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 11,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 12.18,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 9,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 12.17,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 7,
    "GPS": "N",
  },
  {
    "profondeurDtMill": 12.16,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 6,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 12.15,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 4,
    "GPS": "M",
  },
  {
    "profondeurDtMill": 12.14,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 2,
    "GPS": "L",
  },
  {
    "profondeurDtMill": 12.135,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "L",
  },
  {
    "profondeurDtMill": 12.12,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "K",
  },
  {
    "profondeurDtMill": 12.105,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "J",
  },
  {
    "profondeurDtMill": 12.09,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "I",
  },
  {
    "profondeurDtMill": 12.08,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "H",
  },
  {
    "profondeurDtMill": 12.065,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "G",
  },
  {
    "profondeurDtMill": 12.055,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "F",
  },
  {
    "profondeurDtMill": 12.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "E",
  },
  {
    "profondeurDtMill": 12.035,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 12.025,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 12.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 12.005,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "A",
  },
  {
    "profondeurDtMill": 10.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 10.36,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": 1,
    "GPS": "P",
  },
  {
    "profondeurDtMill": 10.33,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "P",
  },
  {
    "profondeurDtMill": 10.315,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "O",
  },
  {
    "profondeurDtMill": 10.255,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "N",
  },
  {
    "profondeurDtMill": 10.24,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "M",
  },
  {
    "profondeurDtMill": 10.18,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "L",
  },
  {
    "profondeurDtMill": 10.165,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "K",
  },
  {
    "profondeurDtMill": 10.135,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "J",
  },
  {
    "profondeurDtMill": 10.12,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "I",
  },
  {
    "profondeurDtMill": 10.105,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "H",
  },
  {
    "profondeurDtMill": 10.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "G",
  },
  {
    "profondeurDtMill": 10.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "F",
  },
  {
    "profondeurDtMill": 10.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 10.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 10.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 8.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 8.36,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "M",
  },
  {
    "profondeurDtMill": 8.3,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "L",
  },
  {
    "profondeurDtMill": 8.255,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "K",
  },
  {
    "profondeurDtMill": 8.195,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "J",
  },
  {
    "profondeurDtMill": 8.165,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "I",
  },
  {
    "profondeurDtMill": 8.135,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "H",
  },
  {
    "profondeurDtMill": 8.105,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "G",
  },
  {
    "profondeurDtMill": 8.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "F",
  },
  {
    "profondeurDtMill": 8.06,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "E",
  },
  {
    "profondeurDtMill": 8.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 8.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 8.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 6.999,
    "15m": "Hors table",
    "12m": "Hors table",
    "9m": "Hors table",
    "6m": "Hors table",
    "3m": "Hors table",
    "GPS": "Hors table",
  },
  {
    "profondeurDtMill": 6.36,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "J",
  },
  {
    "profondeurDtMill": 6.315,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "I",
  },
  {
    "profondeurDtMill": 6.24,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "H",
  },
  {
    "profondeurDtMill": 6.18,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "G",
  },
  {
    "profondeurDtMill": 6.135,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "F",
  },
  {
    "profondeurDtMill": 6.105,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "E",
  },
  {
    "profondeurDtMill": 6.075,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "D",
  },
  {
    "profondeurDtMill": 6.045,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "C",
  },
  {
    "profondeurDtMill": 6.03,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "B",
  },
  {
    "profondeurDtMill": 6.015,
    "15m": "",
    "12m": "",
    "9m": "",
    "6m": "",
    "3m": "",
    "GPS": "A",
  },
];


# Chemin du fichier de sortie JSON sur le bureau
output_file = os.path.join(os.path.expanduser('~'), 'Desktop', 'profondeurDtMille_updated.json')

# Fonction pour supprimer les objets avec toutes les valeurs "Hors table"
def remove_unwanted_entries(data):
    return [entry for entry in data if not all(value == "Hors table" for key, value in entry.items() if key != 'profondeurDtMill')]

# Filtrer les données
filtered_data = remove_unwanted_entries(profondeurDtMille)

# Sauvegarder les données filtrées dans un fichier JSON
with open(output_file, 'w') as file:
    json.dump(filtered_data, file, indent=4)

print(f'Fichier JSON mis à jour enregistré sous : {output_file}')